### ISSUE TITLE
Markdown生成调整

### ISSUE THREAD

**Issue by TeacherTan** [Anselyuki/maimai-search-rs#2]
为了Markdown编辑方便，希望增加一个参数加入多个id，生成一个乐曲列表包含多行乐曲信息。
**示例：**
```
./maimai-search.exe -list 480 11233 11207 466 -m -o Demo.md
```

| 谱面图片                                                         | ID    | 乐曲标题        | 类型 | 分区      | BPM | 演唱/作曲      |
|------------------------------------------------------------------|-------|-----------------|------|-----------|-----|----------------|
| ![HIMITSUスパーク](https://www.diving-fish.com/covers/00480.png) | 480   | HIMITSUスパーク | SD   | 流行&动漫 | 156 | カラスは真っ白 |
| ![Starry Colors](https://www.diving-fish.com/covers/11233.png) | 11233 | Starry Colors | DX   | 舞萌 | 177 | BlackY feat. Risa Yuzuki |
| ![Ether Strike](https://www.diving-fish.com/covers/11207.png) | 11207 | Ether Strike | DX   | 其他游戏 | 156 | Akira Complex |
| ![Jimang Shot](https://www.diving-fish.com/covers/00466.png) | 466   | Jimang Shot | SD   | 东方Project | 164 | じまんぐ  |

**Comment by Anselyuki** [comment]
可以考虑用last标记让id的name支持批量读取
