### ISSUE TITLE
Maybe have problems in pyo3 in Windows

### ISSUE THREAD

**Issue by TeacherTan** [Anselyuki/maimai-search-rs#7]
In README.md in pyo3 in [github](https://github.com/PyO3/pyo3), there are some prepared notice:

> To embed Python into a Rust binary, you need to ensure that your Python installation contains a shared library. The following steps demonstrate how to ensure this (for Ubuntu), and then give some example code which runs an embedded Python interpreter.
> To install the Python shared library on Ubuntu:
> sudo apt install python3-dev 

（在pyo3的官方仓库里，有提及到若需要在RUST中使用python模块，需要先安装python3-dev这个共享库，我不确定在Windows上这个共享库是否原生存在。前提：使用 `pip3 install python3-dev` 是无效的）

**Comment by Anselyuki** [comment]
这个你只要设置了全局变量，就是存在的。windows的python自带这个模块
